## Docker-Compose file is used to start dependent services

version: '3'
services:
  zk:
    image: zookeeper:3.4
    container_name: flowci-agent-debug-zk
    ports:
      - "2181:2181"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: flowci-agent-debug-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"